### ISSUE TITLE
No anchor for release calendar

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#1123] opened 2024-07-01 13:38 UTC
There's no way to form a link to the release calendar:

![image](https://github.com/boostorg/website-v2/assets/1503976/45dae98a-0e34-47a0-8193-5a817bf0c9b8)

**Comment by kennethreitz** [comment] 2024-07-01 13:40
Duplicate of #951

**Comment by kennethreitz** [comment] 2024-07-01 18:11
@vinniefalco anchor tag for `schedule` added to the homepage, which you can preview here: https://www.stage.boost.cppalliance.org/#schedule

**Closed** 2024-07-01 18:11 UTC
