### ISSUE TITLE
Navbar doesn't always highlight the proper nav link

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1199] opened 2024-08-23 05:17 UTC
Example, when going to the "Learn" section, the color changes to the mustard color. when you click on the user guide docs, the leader link color remains mustard, but the link color goes away on the contributor guide docs or review docs.

Do we also want the Join link to light up when going through the sign up process?

We need to verify if other links are not having the correct behavior as well.

The link colors are being set using Django code, so someone who is proficient with that should take a look.

**Comment by rbbeeston** [comment] 2024-10-07 18:46
duplicate of #1200

**Comment by julioest** [comment] 2024-11-08 04:17
Closing as duplicate of #1200

**Closed by julioest** 2024-11-08 04:17 UTC
Labels: Bug, Req. for Launch
