### ISSUE TITLE
Commit history graph is out of date

### ISSUE THREAD

**Issue by ned14** [boostorg/website-v2#934] opened 2024-02-12 21:13 UTC
Compare

https://www.preview.boost.org/libraries/outcome/boost-1-84-0/

to

https://github.com/boostorg/outcome/graphs/commit-activity

**Comment by sdarwin** [comment] 2024-02-12 21:39
Duplicate of https://github.com/cppalliance/temp-site/issues/926 .  Check the page again in a couple days. It should be updated.

**Comment by kennethreitz** [comment] 2024-03-27 22:39
This appears to be resolved now.

**Closed by kennethreitz** 2024-03-27 22:39 UTC
