### ISSUE TITLE
Boost.Utility docs show busted image next to library name

### ISSUE THREAD

**Issue by LegalizeAdulthood** [boostorg/website-v2#942] opened 2024-02-12 22:29 UTC
![image](https://github.com/cppalliance/temp-site/assets/4270863/53376c87-5df7-4617-ad43-90caf1c757c0)

**Comment by joaquintides** [comment] 2024-03-26 17:09
Can't reproduce either in Crome or Firefox, maybe is fixed yet?

**Comment by kennethreitz** [comment] 2024-03-27 21:08
The HTML for this part is as such:

```html
<h1><img src="doc/logo.png" alt="Boost.Utility"></h1>
```

And appears to be coming from the readme. I'll take a look at the readme–rendering code and see if there's anything I can do to correct.

**Comment by vinniefalco** [comment] 2024-03-28 17:41
This is because of the principle that the contents of a Boost library repo are mapped to libs/X where X is the repository name.  The file in question is here:

https://github.com/boostorg/utility/blob/develop/doc/logo.png

**Comment by kennethreitz** [comment] 2024-03-29 19:40
Logging here that `Boost.Atomic` does the same thing, with the same HTML.

**Comment by rbbeeston** [comment] 2024-10-16 18:05
This has been fixed on the front end to hide the broken image link. Setting the relative path to an absolute path should be handled by the maintainers, and can be done on a case by case basis.

**Closed by rbbeeston** 2024-10-16 18:05 UTC

**Comment by vinniefalco** [comment] 2024-10-16 22:11
The solution is never "use an absolute URL"

**Comment by rbbeeston** [comment] 2024-10-17 15:58
It should be an absolute URL, but the images would best be hosted on github alongside the readme, for long term stability.
