### ISSUE TITLE
Add Boost Formal Review Schedule to site

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1356] opened 2024-10-14 19:03 UTC
The following page:
[1.86.0.beta1 release notes not showing](https://github.com/boostorg/website-v2/issues/1171)	https://github.com/boostorg/website-v2/issues/1171
needs to be added to the new site.

Questions: 
Do we want this in the community section? if so, in a new or existing card?
and/or should it be linked from the releases page?

**Comment by vinniefalco** [comment] 2024-10-14 20:43
And if you make a database table you need to import everything. When people are mentioned (for example the submitter or the review manager) I want to see an avatar.

**Comment by GregKaleka** [comment] 2024-11-05 22:25
I'm a bit confused by this ticket. The title seems to indicate it might be a duplicate of #695, but then the description seems to be asking to add... another ticket as a page on the new website?

**Comment by GregKaleka** [comment] 2024-11-20 15:46
I'm closing this as a duplicate of #695.

**Closed by GregKaleka** 2024-11-20 15:46 UTC
